---
name: Alien-wxWidgets
version: 0.41
author:
  - 'Mattia Barbon <mbarbon@cpan.org>'
abstract: 'building, finding and using wxWidgets binaries'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Module::Pluggable: 2.6
  perl: 5.006
build_requires:
  Module::Build: 0.26
provides:
  Alien::wxWidgets:
    file: lib/Alien/wxWidgets.pm
    version: 0.41
  Alien::wxWidgets::Utility:
    file: lib/Alien/wxWidgets/Utility.pm
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
